export const SIGN_IN = 'Sign In';
export const SIGN_UP = 'Sign Up';
export const LOGOUT = 'Logout';
export const HOME = 'Home';
export const MAIN = 'Main';
export const PROFILE = 'Profile';
export const SUBMIT = 'Submit';
export const TOPICS = 'Topics';
export const TOPIC = 'Topic';
